// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let result = () => {
    let a = 1, b = 0, temp
    let fibonacci_even_terms = []
    while (a < 4000000){
        if (a % 2 === 0) {
            fibonacci_even_terms.push(a)
        }
        temp = a
        a = a + b
        b = temp
    }
    return fibonacci_even_terms.reduce((sum, currValue) => sum + currValue)
}
console.log(result())